# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.10

# Change runner accordingly.
default:
  tags:
    - asprunner
    #- iee_oe224
    #- intranet
    #    - srmuc01


stages:
  - Static Analysis
  - Build
  - Test
  - Documentation
  - Deploy
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V  # Print out python version for debugging
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt --no-cache-dir


pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - pip install pylint
    - pylint curriculumagent --rcfile=pylintrc --fail-under=8

build:
  allow_failure: true
  stage: Build
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install wheel
    - python setup.py bdist_wheel
    # an alternative approach is to install and run:
    - pip install dist/*
    # run the command here
  artifacts:
    paths:
      - dist/*.whl

tests:
  stage: Test
  parallel: 7
  script:
    - pip install pytest-cov pytest-benchmark
    - pip install pytest-test-groups
    - pip install -r requirements-dev.txt
    - pip install setuptools==69.5.1
    - pytest --cov-report html:cov_html --cov=curriculumagent tests/ --test-group-count $CI_NODE_TOTAL --test-group=$CI_NODE_INDEX
  dependencies: [ ]
  timeout: 4h
  artifacts:
    paths:
      - cov_html/
    when: on_success
    expire_in: 7 days

# This should only run on master branch or if you trigger it in a merge request
testslow:
  stage: Test
  parallel: 2
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest-cov pytest-benchmark
    - pip install pytest-test-groups
    - pytest -v -m "ultra_slow" --cov-report html:cov_html --runslow --test-group-count $CI_NODE_TOTAL --test-group=$CI_NODE_INDEX -s
  timeout: 24h
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
      allow_failure: true
  artifacts:
    paths:
      - cov_html/
    when: on_success
    expire_in: 7 days


pages:
  stage: Documentation
  environment:
    name: Docs
    url: $CI_PAGES_URL
  script:
    - pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
    - mkdir -p docs/api/
    - sphinx-apidoc --separate --module-first --force -o docs/api/ curriculumagent/  [curriculumagent/action_space, curriculumagent/data,curriculumagent/junior/training_data,curriculumagent/junior/training_data, curriculumagent/scripts,curriculumagent/senior/ckpt,curriculumagent/senior/JuniorModel, curriculumagent/submission/action_sets,curriculumagent/submission/ppo-ckpts]
    - sphinx-build -b html docs docs/build
    - cp docs/build -r public
  artifacts:
    paths:
      - public
  only:
    - tags

deploy_package:
  stage: Deploy
  script:
    - rm -rf dist/
    - pip install twine versioneer wheel
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - tags

