# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

stages:
  - Static Analysis
  - Build
  - Test
  - Documentation
  - Deploy
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv==20.13.1
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - pip install pylint
    - pylint curriculumagent --rcfile=pylintrc --fail-under=8
  tags:
    - asprunner

tests:
  stage: Test
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest-cov pytest-benchmark
    - pytest --cov-report html:cov_html --cov=curriculumagent tests/
  dependencies: [ ]
  artifacts:
    paths:
      - cov_html/
    when: on_success
    expire_in: 7 days
  tags:
    - asprunner

build:
  allow_failure: true
  stage: Build
  script:
    - pip install build
    - python -m build
    # run the command here
  artifacts:
    paths:
      - dist/*.whl
  tags:
    - asprunner

pages:
  stage: Documentation
  environment:
    name: Docs
    url: http://phi16231.pages.fraunhofer.de/curriculumagent
  script:
    - pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
    - mkdir -p docs/api/
    - sphinx-apidoc --separate --module-first --force -o docs/api/ curriculumagent/  [curriculumagent/action_space, curriculumagent/data,curriculumagent/junior/training_data,curriculumagent/junior/training_data, curriculumagent/scripts,curriculumagent/senior/ckpt,curriculumagent/senior/JuniorModel, curriculumagent/submission/action_sets,curriculumagent/submission/ppo-ckpts]
    - sphinx-build -b html docs docs/build
    - cp docs/build -r public
  artifacts:
    paths:
     - public
  only:
  - tags
  tags:
    - asprunner

deploy_package:
  stage: Deploy
  script:
    - rm -rf dist/
    - pip install twine versioneer wheel
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
  - tags
  tags:
  - asprunner

# pages:
#   stage: Deploy
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd doc ; make html
#     - mv build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#   tags:
#     - asprunner
