name: CI

on: [push]

jobs:
  pylint:

    runs-on: ubuntu-latest
    steps:
      # Install python and dependencies:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Run pylint
      - name: Run Pylint for checking of Syntax
        run: |
           pylint curriculumagent --rcfile=pylintrc --fail-under=8
      # Run Pytest
  tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ci_index: [0, 1, 2, 3]
        ci_total: [4]
    steps:
      - name: Test with pytest
        run: |
          pip install pytest-cov pytest-benchmark
          pip install pytest-test-groups
          pytest --cov-report html:cov_html --cov=curriculumagent tests/ --test-group-count ${{ matrix.ci_total }} --test-group=${{ matrix.ci_index }}
      - name: Archive Test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Coverage
          path: cov_html/
          retention-days: 7
        if: ${{ always() }}
